version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
#      - "80:80"
      - "8878:80"
    depends_on:
      - app
    container_name: ${CONTAINER_PREFIX}_nginx
  app:
    image: $REGISTRY/dev/app:$CI_COMMIT_SHA
    volumes:
      - ./:/var/www
    container_name: ${CONTAINER_PREFIX}_app
