version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
      - /var/www/e-vlasov-laravel2/.env:/var/www/.env:ro
    ports:
#      - "80:80"
      - "8878:80"
    depends_on:
      - app
    container_name: ${CONTAINER_PREFIX}_nginx
  app:
    image: $REGISTRY/dev/app:$CI_COMMIT_SHA
    env_file:
      - .env
    environment:
      - APP_KEY=$APP_KEY
      - APP_NAME=$APP_NAME
      - APP_ENV=$APP_ENV
      - APP_URL=$APP_URL
      - DB_CONNECTION=$DB_CONNECTION
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_DATABASE=$DB_DATABASE
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - APP_DEBUG=$APP_DEBUG
    volumes:
      - ./:/var/www
    container_name: ${CONTAINER_PREFIX}_app
